name: 'Create pull request'
description: 'Create pull request'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    required: true
  owner:
    description: 'Name of the organization'
    required: true
  repo:
    description: 'Name of repository'
    required: true
  baseBranch:
    description: 'Name of base branch'
    default: 'master'
  headBranch:
    description: 'Name of feature branch'
    required: true
  title:
    description: 'Title of the PR'
    required: true
  body:
    description: 'PR body message'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
